language: java

jdk:
  - openjdk8
  - openjdk11

env:
  - NAME="Test (fail fast)"
    TEST_ONLINE="true"
    SCRIPT_1="./millw -i __.test.test"
  - NAME="Test (keep going)"
    TEST_ONLINE="true"
    SCRIPT_1="./millw -i -k __.test.test"
  - NAME="Publish into local IVY repo"
    TEST_ONLINE="true"
    SCRIPT_1="./millw -i __.publishLocal"

script:
  - "${SCRIPT_1}"
