language: java

jdk:
  - openjdk8
  - openjdk11

env:
  - TEST_ONLINE="true"
    SCRIPT_1="./millw -i __.test.test"
  - TEST_ONLINE="true"
    SCRIPT_1="./millw -i -k __.test.test"
  - TEST_ONLINE="true"
    SCRIPT_1="./millw -i __.publishLocal"

script:
  - "${SCRIPT_1}"
