language: java

script: ./blended-build/build.sh

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/781043d7e4fabc79e78e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
