language: java

sudo: required

services:
  - docker

env:
  -global:
    - DOCKER_HOST=127.0.0.1
    - DOCKER_PORT=2375

before_script:
  - nvm install 4.6
  - node --version

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2

script: ./blended.build/02_compile-and-test.sh

jdk:
  - oraclejdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/781043d7e4fabc79e78e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
