language: java

sudo: false

branches:
  only:
    - itest

before_script:
  - sudo curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - node --version
  - wget http://downloads.typesafe.com/zinc/0.3.11/zinc-0.3.11.tgz
  - tar xzf zinc-0.3.11.tgz
  - ./zinc-0.3.11/bin/zinc -start -nailed
  - cd blended.mgmt.ui && npm install jsdom && cd ..

script: travis_wait ./blended.build/02_compile-and-test.sh

jdk:
  - oraclejdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/781043d7e4fabc79e78e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
