language: scala

scala: 2.12.6

jdk: oraclejdk8

script:
- make travis

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

env:
  global:
    - secure r048egec7DYp2HXockVYQOQru6FsxYZTABzEmTqZxOIRBpE3/c/km8TrSdKU32te7pZVryTGe2J6DK7xa2U2rHmu9H8Z7ah1a4CZzL0daFP8xZGXJ2aUby8Z++5eoav+CVzqyHWYKZtuB/DEhOlVsvx397rJVRhWIBBQVt5sgxY=

