language: java

sudo: required

services:
  - docker

env:
  -global:
    - DOCKER_HOST=127.0.0.1
    - DOCKER_PORT=2375

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2

script: docker run -it -v $(pwd):/home/blended/project -v ~/.m2:/home/blended/.m2 -v ~/.ivy2:/home/blended/.ivy2 --privileged atooni/blended-build

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/781043d7e4fabc79e78e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
