version: 2
jobs:
  prepare:
    shell: /bin/sh -leo pipefail
    working_directory: ~/blended
    docker:
      - image: atooni/build-alpine:1.0
        user: blended
    steps:
      - checkout
      - restore-cache:
          keys:
            - v2-blended-core-$(set -- $(sha1sum ~/blended/build.sbt) ; echo $1)
            - v2-blended-core-
      - run: |
          sbt clean update
          cd ~/blended && npm install xunit-viewer
      - save_cache:
          key: v2-blended-core-$(set -- $(sha1sum ~/blended/build.sbt) ; echo $1)
          paths:
            - ~/.ivy2
            - ~/node_modules

  build:
    shell: /bin/sh -leo pipefail
    working_directory: ~/blended
    docker:
      - image: atooni/build-alpine:0.1
        user: blended
    steps:
      - checkout

      - restore-cache:
          keys:
            - v2-blended-core-$(set -- $(sha1sum ~/blended/build.sbt) ; echo $1)
            - v2-blended-core-

      - run:
          name: Run SBT
          command: |
            bash ~/blended/scripts/batchTest.sh
          environment:
            - SBT_OPTS: -Xmx1024M -XX:MaxMetaspaceSize=512m

      - run:
          name: Save test results
          command: |
            mkdir -p ~/blended/target/test-results/junit/
            find ~/blended -type f -regex ".*/test-reports/.*xml" -exec cp {} ~/blended/target/test-results/junit/ \;
            xunit-viewer --results=~/blended/target/test-results/junit --output=~/blended/target/test-results/junit.html
          when: always

      - store_test_results:
          path: ~/blended/target/test-results

      - store_artifacts:
          path: ~/blended/target/test-results

      - save_cache:
          key: v2-blended-core-$(set -- $(sha1sum ~/blended/build.sbt) ; echo $1)
          paths:
            - ~/.ivy2

workflows:
  version: 2
  build-test:
    jobs:
      - prepare

      - build:
          requires:
            - prepare

