version: 2
jobs:
  build:
    shell: /bin/sh -leo pipefail
    working_directory: ~/blended
    branches:
      only:
        - circleci
    docker:
      - image: atooni/build-alpine:0.1
        user: blended
    steps:
      - checkout

      - restore-cache:
          keys:
            - v1-blended-core-$(set -- $(sha1sum ~/blended/build.sbt) ; echo $1)
            - v1-blended-core-

      - run:
          name: Run SBT
          command: |
            sbt test
            mkdir -p ~/blended/target/test-results/junit/
            find ~/blended -type f -regex ".*/test-reports/.*xml" -exec cp {} ~/blended/target/test-results/junit/ \;
          environment:
            - SBT_OPTS: -Xmx1536M -XX:MaxMetaspaceSize=768m

      - store_test_results:
          path: ~/blended/target/test-results

      - save_cache:
          key: v1-blended-core-$(set -- $(sha1sum ~/blended/build.sbt) ; echo $1)
          paths:
            - ~/.ivy2
