version: 2.1

orbs:
  blended:
    commands:
      persist_dir_to_workspace:
        parameters:
          workspace:
            type: string
          dir:
            type: string
          file:
            type: string
        steps:
          - run:
              name: Package << parameters.dir >>
              command: |
                mkdir -p << parameters.workspace >>
                tar -C << parameters.dir >> -czf << parameters.workspace >>/<< parameters.file >> .

          - persist_to_workspace:
              root: << parameters.workspace >>
              paths:
                - << parameters.file >>

jobs:
  # -----------------------------------------------------------------------------------------------
  # Just prepare the build by running sbt update - this should throw up if any dependencies cannot
  # be resolved.
  # -----------------------------------------------------------------------------------------------
  prepare:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/blended
    docker:
      - image: atooni/build-alpine:1.0
        user: blended
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
            - v3-blended-core-{{ arch }}

      - run:
          name : SBT Update
          command: sbt clean update

      - save_cache:
          key: v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
          paths:
            - /home/blended/.ivy2

  # -----------------------------------------------------------------------------------------------
  # perform the actual compile job. Here we simply run sbt publish local, so that all our modules
  # end up in the local ivy directory
  # -----------------------------------------------------------------------------------------------
  compile:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/blended
    docker:
      - image: atooni/build-alpine:1.0
        user: blended
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
            - v3-blended-core-{{ arch }}

      - run:
          name: Compile
          command: sbt clean publishLocal

      - blended/persist_dir_to_workspace:
          workspace: /tmp/workspace
          dir: /home/blended/.ivy2/local
          file: ivylocal.tgz

  # -----------------------------------------------------------------------------------------------
  # Run all unit tests, produce a coverage report and upload coverage data to codacy
  # we will attach the coverage data and other things to the current workspace, so that
  # we can use it in later jobs within the workflow
  # -----------------------------------------------------------------------------------------------
  unit-test:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/blended
    docker:
      - image: atooni/build-alpine:1.0
        user: blended

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
            - v3-blended-core-{{ arch }}

      - run:
          name: Coverage
          command: |
            bash /home/blended/blended/scripts/batchTest.sh
          environment:
            - TEST_ONLINE: true
            - SBT_OPTS: -Xmx1024M -XX:MaxMetaspaceSize=512m

      - run:
          name: Coverage Report
          command: sbt coverageReport coverageAggregate codacyCoverage

      - run:
          name: Save test results
          command: |
            mkdir -p /home/blended/blended/target/test-results/junit/
            find /home/blended/blended -type f -regex ".*/test-reports/.*xml" -exec cp {} /home/blended/blended/target/test-results/junit/ \;
            xunit-viewer --results=/home/blended/blended/target/test-results/junit --output=/home/blended/blended/target/test-results/junit.html
          when: always

      - store_test_results:
          path: /home/blended/blended/target/test-results

      - store_artifacts:
          path: /home/blended/blended/target/test-results
          prefix: XUnit

      - store_artifacts:
          path: /home/blended/blended/target/scala-2.12/scoverage-report
          prefix: coverage

      - store_artifacts:
          path: /home/blended/blended/target/testlog
          prefix: testlog

      - blended/persist_dir_to_workspace:
          workspace: /tmp/workspace
          dir: /home/blended/blended/target
          file: unittest.tgz

  # -----------------------------------------------------------------------------------------------
  # Generate and deploy the current documentation
  # -----------------------------------------------------------------------------------------------
  site:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/blended
    docker:
      - image: atooni/build-alpine:1.0
        user: blended

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
            - v3-blended-core-{{ arch }}

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Extract Workspace
          command: |
            mkdir -p /home/blended/.ivy2/local
            tar -C /home/blended/.ivy2/local -xzf /tmp/worksapce/ivylocal.tgz
            mkdir -p /home/blended/blended/target
            tar -C /home/blended/blended/target -xzf /tmp/workspace/unittest.tgz

      - run:
          name: Build docs
          command: sbt unidoc jbakeSite

workflows:
  version: 2.1
  blended:
    jobs:
      - prepare

      - compile:
          requires:
            - prepare
      - unit-test:
          context: blended
          requires:
            - compile

