version: 2.1

orbs:
  blended:
    commands:
      # ----------------------------------------------------------------------------------------
      # persist a complete directory incl. sub directories to the workspace using a tar file
      # ----------------------------------------------------------------------------------------
      persist_dir_to_workspace:
        parameters:
          workspace:
            type: string
          dir:
            type: string
          file:
            type: string
        steps:
          - run:
              name: Package << parameters.dir >>
              command: |
                mkdir -p << parameters.workspace >>
                tar -C << parameters.dir >> -cvzf << parameters.workspace >>/<< parameters.file >> .

          - persist_to_workspace:
              root: << parameters.workspace >>
              paths:
                - << parameters.file >>

      # ----------------------------------------------------------------------------------------
      # Update gh-pages with the content of a given directory
      # ----------------------------------------------------------------------------------------
      deploy_gh_pages:
        parameters:
          dir:
            type: string
          git_user_name:
            type: string
            default: Blended CI
          git_user_mail:
            type: string
            default: ci@wayofquality.de

        steps:
          - run:
              name: Deploy Site
              command: |
                git config user.email "<< parameters.git_user_mail >>"
                git config user.name "<< parameters.git_user_name >>"
                git checkout --orphan gh-pages
                git reset
                git add -f << parameters.dir >>
                git commit -m "[skip ci] Deploy Site, build number ${CIRCLE_BUILD_NUM}"
                git filter-branch -f --prune-empty --subdirectory-filter << parameters.dir >>
                git clean -f -f -d
                git push -f origin gh-pages

      # ----------------------------------------------------------------------------------------
      # Update gh-pages with the content of a given directory
      # ----------------------------------------------------------------------------------------
      clone_and_build:
        parameters:
          url:
            type: string
          dir:
            type: string
          src_archive:
            type: string
            default: ivylocal.tgz
          archive:
            type: string
          with_test:
            type: string
            default: "true"
        steps:
          - checkout

          - restore_cache:
              keys:
                - v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
                - v3-blended-core-{{ arch }}

          - attach_workspace:
              at: /tmp/workspace

          - run:
              name: Extract Workspace
              command: |
                mkdir -p /home/blended/.ivy2/local
                for n in << parameters.src_archive >> ; do
                  tar -C /home/blended/.ivy2/local -xvzf /tmp/workspace/$n
                done

          - run:
              name: Clone
              command: |
                git clone << parameters.url >> << parameters.dir>>

          - run:
              name: Build
              command: |
                cd << parameters.dir >>
                sbt clean update publishLocal
                if [ "true" = "<< parameters.with_test >>" ]; then
                  sbt test
                fi

          - persist_dir_to_workspace:
              workspace: /tmp/workspace
              dir: /home/blended/.ivy2/local
              file: << parameters.archive >>

jobs:
  # -----------------------------------------------------------------------------------------------
  # Just prepare the build by running sbt update - this should throw up if any dependencies cannot
  # be resolved.
  # -----------------------------------------------------------------------------------------------
  prepare:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/blended
    docker:
      - image: atooni/build-alpine:1.0.1
        user: blended
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
            - v3-blended-core-{{ arch }}

      - run:
          name : SBT Update
          command: sbt clean update

      - save_cache:
          key: v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
          paths:
            - /home/blended/.ivy2

  # -----------------------------------------------------------------------------------------------
  # perform the actual compile job. Here we simply run sbt publish local, so that all our modules
  # end up in the local ivy directory
  # -----------------------------------------------------------------------------------------------
  compile:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/blended
    docker:
      - image: atooni/build-alpine:1.0.1
        user: blended
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
            - v3-blended-core-{{ arch }}

      - run:
          name: Compile
          command: sbt clean publishLocal

      - blended/persist_dir_to_workspace:
          workspace: /tmp/workspace
          dir: /home/blended/.ivy2/local
          file: ivylocal.tgz

  # -----------------------------------------------------------------------------------------------
  # Run all unit tests, produce a coverage report and upload coverage data to codacy
  # we will attach the coverage data and other things to the current workspace, so that
  # we can use it in later jobs within the workflow
  # -----------------------------------------------------------------------------------------------
  unit-test:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/blended
    resource_class: medium+
    docker:
      - image: atooni/build-alpine:1.0.1
        user: blended

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
            - v3-blended-core-{{ arch }}

      - run:
          name: Coverage
          command: sbt clean update coverageOn test
          environment:
            - TEST_ONLINE: true
            - SBT_OPTS: -Xmx3072m -XX:MaxMetaspaceSize=1536m

      - run:
          name: Coverage Report
          command: sbt coverageReport coverageAggregate codacyCoverage
          environment:
            - SBT_OPTS: -Xmx3072m -XX:MaxMetaspaceSize=1536m

      - run:
          name: Save test results
          command: |
            mkdir -p /home/blended/blended/target/test-results/junit/
            find /home/blended/blended -type f -regex ".*/test-reports/.*xml" -exec cp {} /home/blended/blended/target/test-results/junit/ \;
          when: always

      - store_test_results:
          path: /home/blended/blended/target/test-results

      - store_artifacts:
          path: /home/blended/blended/target/test-results
          prefix: XUnit

      - store_artifacts:
          path: /home/blended/blended/target/scala-2.12/scoverage-report
          prefix: coverage

      - store_artifacts:
          path: /home/blended/blended/target/testlog
          prefix: testlog

      - blended/persist_dir_to_workspace:
          workspace: /tmp/workspace
          dir: /home/blended/blended/target
          file: unittest.tgz

  # -----------------------------------------------------------------------------------------------
  # Generate and deploy the current documentation
  # -----------------------------------------------------------------------------------------------
  site:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/blended
    docker:
      - image: atooni/build-alpine:1.0.1
        user: blended

    steps:
      - add_ssh_keys:
          fingerprints:
            - "a2:b9:c0:32:b9:d8:24:95:4c:a2:7d:94:e6:6b:85:8e"

      - checkout

      - restore_cache:
          keys:
            - v3-blended-core-{{ arch }}-{{ checksum "build.sbt" }}
            - v3-blended-core-{{ arch }}

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Extract Workspace
          command: |
            mkdir -p /home/blended/.ivy2/local
            tar -C /home/blended/.ivy2/local -xzf /tmp/workspace/ivylocal.tgz
            mkdir -p /home/blended/blended/target
            tar -C /home/blended/blended/target -xvzf /tmp/workspace/unittest.tgz

      - run:
          name: Build docs
          command: sbt unidoc jbakeSite

      - blended/deploy_gh_pages:
          dir: target/site

  # -----------------------------------------------------------------------------------------------
  # Checkout and build the integration test support
  # -----------------------------------------------------------------------------------------------
  itest-support:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/itest
    docker:
      - image: atooni/build-alpine:1.0.1
        user: blended

    steps:
      - blended/clone_and_build:
          url: ssh://git@github.com/woq-blended/blended.itestsupport.git
          dir: itest
          archive: ivylocal-itest.tgz

  # -----------------------------------------------------------------------------------------------
  # Checkout and build the management UI
  # -----------------------------------------------------------------------------------------------
  mgmt-ui:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/ui
    docker:
      - image: atooni/build-alpine:1.0.1
        user: blended

    steps:
      - blended/clone_and_build:
          url: ssh://git@github.com/woq-blended/blended.mgmt.ui.git
          dir: ui
          archive: ivylocal-ui.tgz

  # -----------------------------------------------------------------------------------------------
  # Build the demo container's
  # -----------------------------------------------------------------------------------------------
  demo-container:
    shell: /bin/sh -leo pipefail
    working_directory: /home/blended/container
    docker:
      - image: atooni/build-alpine:1.0.1
        user: blended

    steps:
      - blended/clone_and_build:
          url: ssh://git@github.com/woq-blended/blended.container.git
          dir: container
          src_archive: ivylocal-ui.tgz ivylocal-itest.tgz
          archive: ivylocal-ct.tgz
          with_test: "false"

# -----------------------------------------------------------------------------------------------
# Put everything together in a workflow
# -----------------------------------------------------------------------------------------------
workflows:
  version: 2.1
  blended:
    jobs:
      # -----------------------------------------------------------------------------------------
      - prepare:
          filters:
            branches:
              only:
                - master

      # -----------------------------------------------------------------------------------------
      - compile:
          filters:
            branches:
              only:
                - master
          requires:
            - prepare

      # -----------------------------------------------------------------------------------------
      - unit-test:
          filters:
            branches:
              only:
                - master
          context: blended
          requires:
            - compile

      # -----------------------------------------------------------------------------------------
      - site:
          filters:
            branches:
              only:
                - master
          context: blended
          requires:
            - unit-test

      # -----------------------------------------------------------------------------------------
      - itest-support:
          filters:
            branches:
              only:
                - master
          context: blended
          requires:
            - compile

      # -----------------------------------------------------------------------------------------
      - mgmt-ui:
          filters:
            branches:
              only:
                - master
          context: blended
          requires:
            - compile

      # -----------------------------------------------------------------------------------------
      - demo-container:
          filters:
            branches:
              only:
                - master
          context: blended
          requires:
            - mgmt-ui
            - itest-support
