version: 2
jobs:
  build:
    branches:
      only:
        - circleci
    docker:
      - image: circleci/openjdk:8-stretch-node-browsers-legacy 
    steps:
      - checkout
      - run: echo "Hello CircleCi"
