version: 2
jobs:
  build:
    shell: /bin/sh -leo pipefail
    working_directory: ~/blended
    branches:
      only:
        - circleci
    docker:
      - image: atooni/build-alpine:0.1
        user: blended
    steps:
      - checkout
      - restore-cache:
          keys: 
            - v1-blended-core-$(set -- $(sha1sum ~/blended/build.sbt) ; echo $1)
            - v1-blended-core-
      - run: sbt test
      - save_cache:
          key: v1-blended-core-$(set -- $(sha1sum ~/blended/build.sbt) ; echo $1)
          paths:
            - ~/.ivy2
