title: Blended
description: The website for the Blended project
plugins:
- asciidoctor-diagram
- jekyll-asciidoc
exclude:
- LICENSE.adoc
- README.adoc
asciidoc:
  require_front_matter_header: true
keep_files:
- coverage
- scaladoc
- images
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    idseparator: _
    icons: font
    imagesdir: /images
