title: Jekyll AsciiDoc Quickstart
description: The Jekyll AsciiDoc Quickstart project is a leg-up in starting your own website hosted on GitHub with content based in AsciiDoc.
plugins:
- jekyll-asciidoc
exclude:
- LICENSE.adoc
- README.adoc
asciidoc:
  require_front_matter_header: true
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    idseparator: _
    icons: font